version: '3.7'

services:
  opencart: &opencart
    build: &build
      context: ./docker
      dockerfile: Dockerfile
      args:
        opencart_version: "2.3.0.2"
    depends_on:
      - mysql
    ports:
      - 80:80
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ./upload/admin/controller/extension/payment/begatewayerip.php:/var/www/html/admin/controller/extension/payment/begatewayerip.php
      - ./upload/admin/language/en-gb/extension/payment/begatewayerip.php:/var/www/html/admin/language/en-gb/extension/payment/begatewayerip.php
      - ./upload/admin/language/ru-ru/extension/payment/begatewayerip.php:/var/www/html/admin/language/ru-ru/extension/payment/begatewayerip.php
      - ./upload/admin/view/image/payment/raschet.png:/var/www/html/admin/view/image/payment/raschet.png
      - ./upload/admin/view/template/payment/begatewayerip.tpl:/var/www/html/admin/view/template/payment/begatewayerip.tpl
      - ./upload/catalog/controller/extension/payment/begatewayerip.php:/var/www/html/catalog/controller/extension/payment/begatewayerip.php
      - ./upload/catalog/language/en-gb/extension/payment/begatewayerip.php:/var/www/html/catalog/language/en-gb/extension/payment/begatewayerip.php
      - ./upload/catalog/language/ru-ru/extension/payment/begatewayerip.php:/var/www/html/catalog/language/ru-ru/extension/payment/begatewayerip.php
      - ./upload/catalog/model/extension/payment/begatewayerip.php:/var/www/html/catalog/model/extension/payment/begatewayerip.php
      - ./upload/catalog/view/theme/default/template/extension/payment/begatewayerip.tpl:/var/www/html/catalog/view/theme/default/template/extension/payment/begatewayerip.tpl

    restart: always

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /var/lib/mysql
      - ./docker/etc/mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: opencart
